"""
ONNX export module
Exports trained CatBoost models to ONNX format for MetaTrader 5
"""

import os
from pathlib import Path
from typing import Tuple, List
import numpy as np


def export_to_onnx(
    model_main,
    model_meta,
    config: dict,
    r2_score: float
) -> Tuple[Path, Path]:
    """
    Export trained models to ONNX format
    
    Args:
        model_main: Main CatBoost model (trading signals)
        model_meta: Meta CatBoost model (cluster filtering)
        config: Configuration dictionary
        r2_score: Model R² score for filename
        
    Returns:
        Tuple of (main_model_path, meta_model_path)
    """
    # Create output directory
    output_dir = Path(config['export']['paths']['onnx'])
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate filenames
    symbol = config['symbol']['name']
    direction = config['trading']['direction']
    r2_str = f"{r2_score:.4f}".replace('.', '_')
    
    main_filename = f"{symbol}_{direction}_main_r2_{r2_str}.onnx"
    meta_filename = f"{symbol}_{direction}_meta_r2_{r2_str}.onnx"
    
    main_path = output_dir / main_filename
    meta_path = output_dir / meta_filename
    
    print(f"\n💾 Exporting to ONNX...")
    
    # Export main model
    try:
        model_main.save_model(
            str(main_path),
            format='onnx',
            export_parameters={
                'onnx_domain': config['export']['onnx']['domain'],
                'onnx_model_version': config['export']['onnx']['model_version'],
                'onnx_graph_name': f'{symbol}_main'
            }
        )
        print(f"   ✅ Main model: {main_filename}")
    except Exception as e:
        print(f"   ❌ Main model export failed: {e}")
        raise
    
    # Export meta model
    try:
        model_meta.save_model(
            str(meta_path),
            format='onnx',
            export_parameters={
                'onnx_domain': config['export']['onnx']['domain'],
                'onnx_model_version': config['export']['onnx']['model_version'],
                'onnx_graph_name': f'{symbol}_meta'
            }
        )
        print(f"   ✅ Meta model: {meta_filename}")
    except Exception as e:
        print(f"   ❌ Meta model export failed: {e}")
        raise
    
    # Generate MQL include file
    mqh_path = _generate_mql_include(config, main_filename, meta_filename)
    print(f"   ✅ MQL include: {mqh_path.name}")
    
    print(f"\n📁 Exported files:")
    print(f"   {main_path}")
    print(f"   {meta_path}")
    print(f"   {mqh_path}")
    
    return main_path, meta_path


def _generate_mql_include(
    config: dict,
    main_filename: str,
    meta_filename: str
) -> Path:
    """
    Generate MQL5 include file with model configuration
    
    Args:
        config: Configuration dictionary
        main_filename: Main model filename
        meta_filename: Meta model filename
        
    Returns:
        Path to generated .mqh file
    """
    symbol = config['symbol']['name']
    periods = config.get('periods', [5, 35, 65, 95, 125, 155, 185, 215, 245, 275])
    meta_periods = config.get('periods_meta', [5])
    
    # MQL5 code template
    mqh_content = f"""//+------------------------------------------------------------------+
//| {symbol} Model Configuration                                      |
//| Auto-generated by FuncXauusd export system                       |
//+------------------------------------------------------------------+

#property copyright "FuncXauusd Trading System"
#property version   "1.00"

// Model filenames
#define MODEL_MAIN_FILE "{main_filename}"
#define MODEL_META_FILE "{meta_filename}"

// Feature periods for main model
int Periods{symbol.replace('-', '_')}[] = {{
    {', '.join(map(str, periods))}
}};

// Feature periods for meta model
int PeriodsMeta{symbol.replace('-', '_')}[] = {{
    {', '.join(map(str, meta_periods))}
}};

// Number of features
#define N_FEATURES_MAIN {len(periods)}
#define N_FEATURES_META {len(meta_periods)}

//+------------------------------------------------------------------+
//| Fill main features array                                          |
//+------------------------------------------------------------------+
void fill_arrays_main(double &features[], const double &close[])
{{
    ArrayResize(features, N_FEATURES_MAIN);
    
    for(int i = 0; i < N_FEATURES_MAIN; i++)
    {{
        int period = Periods{symbol.replace('-', '_')}[i];
        features[i] = CalculateStd(close, period);
    }}
}}

//+------------------------------------------------------------------+
//| Fill meta features array                                          |
//+------------------------------------------------------------------+
void fill_arrays_meta(double &features[], const double &close[])
{{
    ArrayResize(features, N_FEATURES_META);
    
    for(int i = 0; i < N_FEATURES_META; i++)
    {{
        int period = PeriodsMeta{symbol.replace('-', '_')}[i];
        features[i] = CalculateSkewness(close, period);
    }}
}}

//+------------------------------------------------------------------+
//| Calculate standard deviation                                      |
//+------------------------------------------------------------------+
double CalculateStd(const double &data[], int period)
{{
    if(period <= 0 || period > ArraySize(data))
        return 0.0;
    
    double sum = 0.0;
    for(int i = 0; i < period; i++)
        sum += data[i];
    
    double mean = sum / period;
    
    double variance = 0.0;
    for(int i = 0; i < period; i++)
    {{
        double diff = data[i] - mean;
        variance += diff * diff;
    }}
    
    variance /= period;
    
    return MathSqrt(variance);
}}

//+------------------------------------------------------------------+
//| Calculate skewness                                                |
//+------------------------------------------------------------------+
double CalculateSkewness(const double &data[], int period)
{{
    if(period <= 0 || period > ArraySize(data))
        return 0.0;
    
    // Calculate mean
    double sum = 0.0;
    for(int i = 0; i < period; i++)
        sum += data[i];
    double mean = sum / period;
    
    // Calculate std
    double variance = 0.0;
    for(int i = 0; i < period; i++)
    {{
        double diff = data[i] - mean;
        variance += diff * diff;
    }}
    double std = MathSqrt(variance / period);
    
    if(std == 0.0)
        return 0.0;
    
    // Calculate skewness
    double m3 = 0.0;
    for(int i = 0; i < period; i++)
    {{
        double z = (data[i] - mean) / std;
        m3 += z * z * z;
    }}
    
    return m3 / period;
}}

//+------------------------------------------------------------------+
//| Configuration parameters                                          |
//+------------------------------------------------------------------+
#define SYMBOL "{symbol}"
#define DIRECTION "{config['trading']['direction']}"
#define STOP_LOSS {config['trading']['risk']['stop_loss']}
#define TAKE_PROFIT {config['trading']['risk']['take_profit']}
#define RISK_PER_TRADE {config['trading']['risk']['risk_per_trade']}
#define MAX_POSITIONS {config['trading']['risk']['max_positions']}
#define SPREAD_LIMIT {config['trading']['risk']['spread_limit']}

//+------------------------------------------------------------------+
"""
    
    # Save to file
    output_dir = Path(config['export']['paths']['onnx'])
    mqh_filename = f"{symbol}_ModelInclude.mqh"
    mqh_path = output_dir / mqh_filename
    
    with open(mqh_path, 'w', encoding='utf-8') as f:
        f.write(mqh_content)
    
    return mqh_path


def load_onnx_model(model_path: Path):
    """
    Load ONNX model for verification (requires onnxruntime)
    
    Args:
        model_path: Path to ONNX model
        
    Returns:
        ONNX inference session
    """
    try:
        import onnxruntime as ort
        
        session = ort.InferenceSession(str(model_path))
        
        return session
    except ImportError:
        print("⚠️ onnxruntime not installed, skipping verification")
        return None
    except Exception as e:
        print(f"❌ Error loading ONNX model: {e}")
        return None


def verify_onnx_export(
    model_path: Path,
    test_input: np.ndarray
) -> bool:
    """
    Verify that ONNX model can make predictions
    
    Args:
        model_path: Path to ONNX model
        test_input: Test input array
        
    Returns:
        True if verification successful
    """
    session = load_onnx_model(model_path)
    
    if session is None:
        return False
    
    try:
        # Get input name
        input_name = session.get_inputs()[0].name
        
        # Make prediction
        result = session.run(None, {input_name: test_input})
        
        print(f"   ✅ ONNX verification passed")
        print(f"      Input shape: {test_input.shape}")
        print(f"      Output shape: {result[0].shape}")
        
        return True
        
    except Exception as e:
        print(f"   ❌ ONNX verification failed: {e}")
        return False


def export_to_cbm(
    model,
    output_path: Path
) -> Path:
    """
    Export model to native CatBoost format
    
    Args:
        model: CatBoost model
        output_path: Output file path
        
    Returns:
        Path to saved model
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    model.save_model(str(output_path), format='cbm')
    
    print(f"   ✅ Saved CBM: {output_path.name}")
    
    return output_path


def create_model_metadata(
    config: dict,
    r2_score: float,
    output_path: Path
) -> Path:
    """
    Create metadata file for exported models
    
    Args:
        config: Configuration dictionary
        r2_score: Model performance score
        output_path: Path to save metadata
        
    Returns:
        Path to metadata file
    """
    import json
    from datetime import datetime
    
    metadata = {
        'export_timestamp': datetime.now().isoformat(),
        'symbol': config['symbol']['name'],
        'timeframe': config['symbol']['timeframe'],
        'direction': config['trading']['direction'],
        'r2_score': r2_score,
        'model_config': {
            'periods': config.get('periods'),
            'meta_periods': config.get('periods_meta'),
            'n_clusters': config.get('n_clusters'),
            'markup': config.get('markup'),
            'depth': config.get('depth'),
            'iterations': config.get('iterations')
        },
        'risk_management': config['trading']['risk'],
        'training_data': {
            'backward': config['data']['backward'],
            'forward': config['data']['forward'],
            'full_forward': config['data']['full_forward']
        }
    }
    
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(metadata, f, indent=2)
    
    print(f"   ✅ Metadata: {output_path.name}")
    
    return output_path